services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./submodules/service/identity/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
