services:
  postgis:
    image: postgis/postgis:18-3.6-alpine
    container_name: postgis
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=spatial_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d spatial_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/spatial/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/01-init.sql # initialize postgis tables
      - ./backend/spatial/src/main/resources/db/data.sql:/docker-entrypoint-initdb.d/02-data.sql # insert initial data

  spatial:
    build:
      context: ./backend
      dockerfile: spatial/Dockerfile
    container_name: spatial
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgis:5432/spatial_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
    depends_on:
      postgis:
        condition: service_healthy

volumes:
  postgres_data: